language: ruby
rvm:
  - 2.1
  gem install ruby_dep -v 1.3.1
install: gem install ruby_dep -v 1.3.1 && gem install jekyll -v 3.6.2 && gem install s3_website
script: jekyll build --source src --destination www
after_success: s3_website push
